// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD1rMVGKtL7eS3xpfVwndBqYRNNjmEZevQ',
    appId: '1:1002852434700:android:cd0250442966878a97bf29',
    messagingSenderId: '1002852434700',
    projectId: 'loginwear-44229',
    databaseURL: 'https://loginwear-44229-default-rtdb.firebaseio.com',
    storageBucket: 'loginwear-44229.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBwICwzjtZeBIW85iWp0n57-d6sUrednJ4',
    appId: '1:1002852434700:ios:ecedb141b4ad8f8c97bf29',
    messagingSenderId: '1002852434700',
    projectId: 'loginwear-44229',
    databaseURL: 'https://loginwear-44229-default-rtdb.firebaseio.com',
    storageBucket: 'loginwear-44229.appspot.com',
    androidClientId: '1002852434700-ab6l906i3fvc8eljpmludjgtukb1slhi.apps.googleusercontent.com',
    iosClientId: '1002852434700-ujufpoio19buqa013lc7uoog8tgga7m9.apps.googleusercontent.com',
    iosBundleId: 'com.example.getxfirebasecrud',
  );
}
